apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: bo@rdCoTom
  POSTGRES_PASSWORD: Bo@rdCo^989
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: bo@rdCoTom
  POSTGRES_NON_ROOT_PASSWORD: Bo@rdCo^989